export default Object.freeze({
  ROLES: {
    BUSINESS_MANAGEMENT: "BUSINESS_MANAGEMENT",
    BOARD_MANAGEMENT: "BOARD_MANAGEMENT",
    STATISTICS_MANAGEMENT: "STATISTICS_MANAGEMENT",
    REQUEST_MANAGEMENT: "REQUEST_MANAGEMENT",
    SETTINGS_MANAGEMENT: "SETTINGS_MANAGEMENT",
  },

  BUSINESS_MANAGEMENT: {
    TICKET_ROLE: "TICKET_ROLE",
    COUNSEL_TYPE_ROLE: "COUNSEL_TYPE_ROLE",
    CUSTOMER_INFO_ROLE: "CUSTOMER_INFO_ROLE",
    CALLBACK_ROLE: "CALLBACK_ROLE",
    NOTIFICATION_ROLE: "NOTIFICATION_ROLE",
    MESSAGE_ROLE: "MESSAGE_ROLE",
    SCRIPT_ROLE: "SCRIPT_ROLE",
  },

  BOARD_MANAGEMENT: {
    BOARD_ROLE: "BOARD_ROLE",
    NOTICE_ROLE: "NOTICE_ROLE",
  },

  STATISTICS_MANAGEMENT: {
    STATISTICS_COUNSEL_TYPE_ROLE: "STATISTICS_COUNSEL_TYPE_ROLE",
    STATISTICS_USER_ROLE: "STATISTICS_USER_ROLE",
  },

  REQUEST_MANAGEMENT: {
    REQUEST_INIT_PWD_APPROVAL: "REQUEST_INIT_PWD_APPROVAL",
  },

  SETTINGS_MANAGEMENT: {
    USER_ROLE: "USER_ROLE",
    CODE_ROLE: "CODE_ROLE",
    PERMISSION_ROLE: "PERMISSION_ROLE",
    ORGANIZATION_ROLE: "ORGANIZATION_ROLE",
    MENU_ROLE: "MENU_ROLE",
    VARIABLE_ROLE: "VARIABLE_ROLE",
    ACCESS_LOG_ROLE: "ACCESS_LOG_ROLE",
    SITE_LINK_ROLE: "SITE_LINK_ROLE",
  },

  TICKET_ROLE: {
    READ: "TICKET_READ",
    SAVE: "TICKET_SAVE",
    ADD: "TICKET_ADD",
    DELETE: "TICKET_DELETE",
  },

  COUNSEL_TYPE_ROLE: {
    READ: "COUNSEL_TYPE_READ",
    SAVE: "COUNSEL_TYPE_SAVE",
    ADD: "COUNSEL_TYPE_ADD",
    DELETE: "COUNSEL_TYPE_DELETE",
  },

  CUSTOMER_INFO_ROLE: {
    READ: "CUSTOMER_INFO_READ",
    SAVE: "CUSTOMER_INFO_SAVE",
    ADD: "CUSTOMER_INFO_ADD",
    DELETE: "CUSTOMER_INFO_DELETE",
  },

  CALLBACK_ROLE: {
    READ: "CALLBACK_READ",
    AUTO: "CALLBACK_AUTO",
    MANUAL: "CALLBACK_MANUAL",
  },

  NOTIFICATION_ROLE: {
    READ: "NOTIFICATION_READ",
    DELETE: "NOTIFICATION_DELETE",
  },

  MESSAGE_ROLE: {
    READ: "MESSAGE_READ",
    WRITE: "MESSAGE_WRITE",
    DELETE: "MESSAGE_DELETE",
  },

  SCRIPT_ROLE: {
    READ: "SCRIPT_READ",
    SAVE: "SCRIPT_SAVE",
  },

  BOARD_ROLE: {
    READ: "BOARD_READ",
    SAVE: "BOARD_SAVE",
    ADD: "BOARD_ADD",
    DELETE: "BOARD_DELETE",
    CATEGORY_MANAGE: "CATEGORY_MANAGE",
  },

  NOTICE_ROLE: {
    READ: "NOTICE_READ",
    SAVE: "NOTICE_SAVE",
    ADD: "NOTICE_ADD",
    DELETE: "NOTICE_DELETE",
  },

  STATISTICS_COUNSEL_TYPE_ROLE: {
    READ: "STATISTICS_COUNSEL_TYPE_READ",
  },

  STATISTICS_USER_ROLE: {
    READ: "STATISTICS_USER_READ",
  },

  USER_ROLE: {
    READ: "USER_READ",
    SAVE: "USER_SAVE",
    ADD: "USER_ADD",
    DELETE: "USER_DELETE",
  },

  CODE_ROLE: {
    READ_SERVICE_CODE: "SERVICE_CODE_READ",
    READ_SYSTEM_CODE: "SYSTEM_CODE_READ",
    SAVE: "CODE_SAVE",
    ADD: "CODE_ADD",
    DELETE: "CODE_DELETE",
  },

  PERMISSION_ROLE: {
    READ: "PERMISSION_READ",
    SAVE: "PERMISSION_SAVE",
    ADD: "PERMISSION_ADD",
    DELETE: "PERMISSION_DELETE",
    GROUP_SETTING: "PERMISSION_GROUP_SETTING",
  },

  ORGANIZATION_ROLE: {
    READ: "ORGANIZATION_READ",
    SAVE: "ORGANIZATION_SAVE",
    ADD: "ORGANIZATION_ADD",
    DELETE: "ORGANIZATION_DELETE",
  },

  MENU_ROLE: {
    READ: "MENU_READ",
    SAVE: "MENU_SAVE",
  },

  VARIABLE_ROLE: {
    READ: "VARIABLE_READ",
    SAVE: "VARIABLE_SAVE",
  },

  ACCESS_LOG_ROLE: {
    READ: "ACCESS_LOG_READ",
  },

  SITE_LINK_ROLE: {
    ADD: "SITE_LINK_ADD",
    DELETE: "SITE_LINK_DELETE",
    SAVE: "SITE_LINK_SAVE",
  },
});
