create table EM_TRAN
(
	TRAN_PR INT(22) auto_increment,
	TRAN_ID VARCHAR(50) null,
	TRAN_PHONE VARCHAR(5) null,
	TRAN_CALLBACK VARCHAR(50) null,
	TRAN_STATUS VARCHAR(50) null,
	TRAN_DATE DATE null,
	TRAN_MSG VARCHAR(500) null,
	TRAN_TYPE VARCHAR(50) null,
	TRAN_REFKEY VARCHAR(20) null,
	TRAN_RSLTDATE DATE null,
	TRAN_REPORTDATE DATE null,
	TRAN_RSLT CHAR(1) null,
	TRAN_NET CHAR(3) null,
	TRAN_ETC1 VARCHAR(500) null,
	TRAN_ETC2 VARCHAR(100) null,
	TRAN_ETC3 VARCHAR(100) null,
	TRAN_ETC4 VARCHAR(100) null,
	TRAN_ETC5 VARCHAR(100) null,
	constraint EM_TRAN_pk
		primary key (TRAN_PR)
);


create table EM_TRAN_MMS
(
	MMS_SEQ INT(22) auto_increment,
	FILE_CNT INT(10) null,
	BUILD_YN CHAR(1) null,
	MMS_BODY VARCHAR(2000) null,
	MMS_SUBJECT VARCHAR(40) null,
	FILE_TYPE1 VARCHAR(3) null,
	FILE_TYPE2 VARCHAR(3) null,
	FILE_TYPE3 VARCHAR(3) null,
	FILE_TYPE4 VARCHAR(3) null,
	FILE_TYPE5 VARCHAR(3) null,
	FILE_NAMES1 VARCHAR(100) null,
	FILE_NAMES2 VARCHAR(100) null,
	FILE_NAMES3 VARCHAR(100) null,
	FILE_NAMES4 VARCHAR(100) null,
	FILE_NAMES5 VARCHAR(100) null,
	SERVICE_DEP1 VARCHAR(3) null,
	SERVICE_DEP2 VARCHAR(3) null,
	SERVICE_DEP3 VARCHAR(3) null,
	SERVICE_DEP4 VARCHAR(3) null,
	SERVICE_DEP5 VARCHAR(3) null,
	SKN_FILE_NAME VARCHAR(255) null,
	constraint EM_TRAN_MMS_pk
		primary key (MMS_SEQ)
);


create table EM_TRAN_RCEPT
(
	SMS_SN INT(22) auto_increment,
	SENDER VARCHAR(15) null,
	RCVER VARCHAR(15) null,
	SMS_SJ VARCHAR(50) null,
	SMS_CONTENTS VARCHAR(4000) null,
	SMS_TYPE INT(38) null,
	SMS_SE VARCHAR(30) null,
	SMS_DATE DATE null,
	SMS_PR INT(10) null,
	UPLOAD_CD VARCHAR(100) null,
	UPLOAD_SN INT(22) null,
	RECV_GUBUN VARCHAR(15) null,
	ETC01 VARCHAR(3000) null,
	USE_AT VARCHAR(1) null,
	REG_DT DATE null,
	REGUSR VARCHAR(20) null,
	UPD_DT DATE null,
	UPDUSR VARCHAR(20) null,
	constraint EM_TRAN_RCEPT_pk
		primary key (SMS_SN)
);

