spring:
  config:
    activate:
      on-profile: local-hjbang
  datasource:
    main:
      url: jdbc:mariadb://localhost:3307/wecoms_dev?serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=utf8&useSSL=false
      username: wecoms_dev
      password: wecoms_dev
      driver-class-name: org.mariadb.jdbc.Driver
      hikari:
        maximum-pool-size: 5
        connection-timeout: 20000
      jpa:
        show-sql: true
        hibernate:
          ddl-auto: update
          format-sql: false
com:
  wecoms24:
    flow:
      isMasterServer: true
      redis:
        enable: true
        host: localhost
        port : 6379