spring:
  config:
    activate:
      on-profile: local-hschoi
  datasource:
    main:
      url: jdbc:mariadb://localhost:3309/flow_dev?serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
      username: iotree_dev
      password: iotree1234
      driver-class-name: org.mariadb.jdbc.Driver
      hikari:
        maximum-pool-size: 5
        connection-timeout: 20000
      jpa:
        show-sql: true
        hibernate:
          ddl-auto: update
          format-sql: false
    chemp:
      url: jdbc:mariadb://localhost:3309/nechemp?serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=utf8&useSSL=false
      username: nechemp
      password: nechemp
      driver-class-name: org.mariadb.jdbc.Driver
      hikari:
        maximum-pool-size: 5
        connection-timeout: 20000
com:
  wecoms24: 
    flow: 
       isMasterServer: true
       redis: 
         enable: true
         host: localhost
         port : 6379