const Menu = Object.freeze({
  CALL_CONSULT: { name: "CALL_CONSULT", label: "전화상담" },
  CHAT_CONSULT: { name: "CHAT_CONSULT", label: "채팅상담" },
  TASK_MANAGE: { name: "TASK_MANAGE", label: "업무 관리" },
  TICKET_MANAGE: { name: "TICKET_MANAGE", label: "티켓 관리" },
  CONSULT_TYPE_MANAGE: { name: "CONSULT_TYPE_MANAGE", label: "상담유형 관리" },
  MISSED_CALL_MANAGE: { name: "MISSED_CALL_MANAGE", label: "호놓침 관리" },
  BOARD_MANAGE: { name: "BOARD_MANAGE", label: "게시판 관리" },
  BOARD: { name: "BOARD", label: "게시판" },
  BOARD_SETTINGS: { name: "BOARD_SETTINGS", label: "게시판 설정" },
  SETTINGS: { name: "SETTINGS_MENU", label: "설정" },
  USER_MANAGE: { name: "USER_MANAGEMENT", label: "사용자 관리" },
  PERMISSION_MANAGE: { name: "AUTH_ROLE_MANAGEMENT", label: "권한 관리" },
  CODE_MANAGE: { name: "CODE_MANAGEMENT", label: "코드 관리" },
  NOTICE: { name: "NOTICE", label: "공지사항" },
  ORG_MANAGE: { name: "ORGANIZATION_MANAGEMENT", label: "조직 관리" },
  PROFILE_MANAGE: { name: "PROFILE_MANAGE", label: "프로필 관리" },
  MENU_MANAGE: { name: "MENU_MANAGEMENT", label: "메뉴 관리" },
  SYSTEM_VARIABLE_MANAGE: { name: "VARIABLE_MANAGEMENT", label: "시스템변수 관리" },
  COMPANY_MANAGE: { name: "COMPANY_MANAGE", label: "업체 관리" },
  STATISTICS_BY_COUNSEL_TYPES: { name: "STATISTICS_BY_COUNSEL_TYPES", label: "상담유형별 티켓통계" },
  STATISTICS_BY_USERS: { name: "STATISTICS_BY_USERS", label: "상담사별 티켓통계" },
  CALLBACK_MANAGE: { name: "CALLBACK_MANAGE", label: "콜백 관리" },
  NOTIFICATION_MANAGE: { name: "NOTIFICATION_MANAGE", label: "알림 관리" },
  ACCESS_LOG_MANAGEMENT: { name: "ACCESS_LOG_MANAGEMENT", label: "접속로그 관리" },
  MESSAGE_MANAGE: { name: "MESSAGE_MANAGE", label: "쪽지 관리" },
  SCRIPT_MANAGE: { name: "SCRIPT_MANAGE", label: "스크립트 관리" },
  SITE_LINK_MANAGE: { name: "SITE_LINK_MANAGEMENT", label: "사이트링크 관리" },
});

export { Menu };
